version: '3.7' # composeファイルのバーション指定
services:
  gin-test: # service名
    build: . # ビルドに使用するDockerfileがあるディレクトリ指定
    tty: true # コンテナの起動永続化
    volumes:
      - .:/go/gin-test # マウントディレクトリ指定
    ports:
      - "8080:8080"
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: gin-test
      POSTGRES_PASSWORD: gin-test
      POSTGRES_DB: gin-test
    ports:
      - 5432:5432
